### ISSUE TITLE
[Suggestion] Change duplicate file handling

### ISSUE THREAD

**Issue by ghost** [uget/uget#12]
Currently, duplicate files are handled like this:

image.png
image.png.0
image.png.1
image.png.2
image.png.3

This does not work well, for Windows especially, because of file format associations. I end up having to use a renamer program to fix it.

I would instead like to see it handled in the following way.

image.png
image.2.png
image.3.png
image.4.png
image.5.png

0 and 1 are skipped for greater clarity, so it's more obvious that image.2.png is the first duplicate, not the third.

**Comment by muja** [comment]
You must have confused this with another project. For files with the same name, this project will not download the file unless the user specifies it via flags.
