### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by Eric-Sjt** [uget/uget#15]
First, how to automatically update tracker?

Second, I am using uget 2.2.2 on windows.In the beginning, I choose ''add a torrent'' but uget can't identify the torrent file. Then I open torrent with uget, uget show the url is the path of torrent, but it can not download the file. Then I open it with aria2 directly, it is fast.

**Comment by muja** [comment]
Hi, this question is probably not related to this project. You are probably referring to https://ugetdm.com/. As such, I cannot help you in this matter.
