### ISSUE TITLE
Uget Not Showing The correct tray icon on gentoo

### ISSUE THREAD

**Issue by javashin** [uget/uget#4]
https://imgur.com/a/5zLin
please hellp me with a solution also this behavior happen to me on freebsd on freebsd dont show the tray icon at all .

**Comment by javashin** [comment]
EDIT look at the icon "?" on the image that icon is uget

**Comment by muja** [comment]
Hi, this project has nothing to do with uGet, so unfortunately I cannot help. You closed this issue, so have you solved it?
