### ISSUE TITLE
Uget crash when i download four file.

### ISSUE THREAD

**Issue by LithiumHydrogen** [uget/uget#5]
I am  sorry, my English is poor. I will try my best to describe the problem .I install uget from centos yum.
Uget is a powerful free software ,however,when i download 4 file at the same time. The uget was crash,it broken, i have to kill it.

**Comment by muja** [comment]
Hi, you have confused this for another project. This project has nothing to do with the one from ugetdm.com.

**Comment by JulianLai** [comment]
@muja My bad.
